services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=restaurante
      - MYSQL_ROOT_PASSWORD=1907
      - MYSQL_USER=gabs
      - MYSQL_PASSWORD=1907
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wit
    ports:
      - "8080:80"

  node:
    image: node:lts
    container_name: node
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    command: sh -c "npm install && npm start"
    volumes:
      - ../PAP-BackEnd/:/home/node/ap
    ports:
      - '3000:3000'